### PR TITLE
Adding DoesTypeTest translates

### PR DESCRIPTION
**Pull request by PalumboN**
Closes https://github.com/mumuki/mumuki-platform/issues/237

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Ooops! It is failing because we have not updated the ruby version yet.

**Comment by flbulgarelli** [comment]
@PalumboN I have just pushed a fix to master. Could you rebase your pull request, please?

**Comment by PalumboN** [comment]
Done, but still is broken :cry:

**Comment by flbulgarelli** [comment]
Now it should work

**Pull request merged**
